import type { Category } from "./types";
export const INTENT_TRAINING: { text: string; label: Category }[] = [
  { label: "JOB_OPPORTUNITY", text: "We are hiring for an open position and would like you to apply. vacancy opening role join our team employment opportunity" },
  { label: "JOB_OPPORTUNITY", text: "لدينا شاغر ونرغب بانضمامك للفريق. فرصة وظيفية وظيفة متاحة التقديم على منصب نبحث عن موظف" },
  { label: "JOB_OPPORTUNITY", text: "Your profile may be a fit for a role currently open with our company. interested candidates are invited to apply" },
  { label: "RECRUITER_OUTREACH", text: "I came across your profile and your background caught my attention. I would like to discuss an opportunity with you recruiter talent acquisition" },
  { label: "RECRUITER_OUTREACH", text: "اطلعت على ملفك وخبرتك ونرغب بالتواصل معك لمناقشة فرصة محتملة لدينا. فريق الاستقطاب المواهب" },
  { label: "RECRUITER_OUTREACH", text: "Your experience looks relevant to something we are working on. Are you open to a quick conversation about a career opportunity?" },
  { label: "APPLICATION_RECEIVED", text: "Thank you for applying. We successfully received your application and resume. application confirmation candidate submission" },
  { label: "APPLICATION_RECEIVED", text: "شكرا لتقديمك تم استلام طلبك والسيرة الذاتية بنجاح وسيتم مراجعته من فريق التوظيف" },
  { label: "APPLICATION_UPDATE", text: "Your application is under review. We are reviewing candidates and will update you on the next step soon." },
  { label: "APPLICATION_UPDATE", text: "طلبك تحت المراجعة تحديث حالة الترشيح ما زلنا نراجع المتقدمين وسيتم التواصل لاحقا" },
  { label: "INTERVIEW", text: "We would like to invite you to an interview. Please choose a time to speak with the hiring manager or team." },
  { label: "INTERVIEW", text: "نود دعوتك لمقابلة شخصية وتحديد موعد للتحدث مع الفريق. يرجى تأكيد الوقت المناسب" },
  { label: "INTERVIEW", text: "The team enjoyed reviewing your background and would like to schedule a conversation with you next week." },
  { label: "ASSESSMENT", text: "Please complete the online assessment, technical test, coding challenge or take-home task before the deadline." },
  { label: "ASSESSMENT", text: "نرجو إكمال الاختبار أو التقييم الإلكتروني أو المهمة العملية قبل الموعد المحدد" },
  { label: "INTERNSHIP", text: "internship trainee placement summer internship cooperative training practical training program intern opportunity" },
  { label: "INTERNSHIP", text: "فرصة تدريب متدرب تدريب صيفي تدريب تعاوني تمهير تدريب عملي برنامج تدريبي" },
  { label: "GRADUATE_PROGRAM", text: "graduate development program future talent fresh graduate rotational program early careers graduate scheme" },
  { label: "GRADUATE_PROGRAM", text: "برنامج تطوير الخريجين حديثي التخرج مواهب المستقبل برنامج خريجين مسار وظيفي للخريجين" },
  { label: "FREELANCE_PROJECT", text: "freelance paid project contract gig consultant independent contractor short term assignment we need someone to deliver a project" },
  { label: "FREELANCE_PROJECT", text: "نحتاج مستقل لتنفيذ مشروع بمقابل عقد مؤقت عمل حر استشارة مشروع قصير المدة" },
  { label: "TECH_COLLABORATION", text: "We saw your backend API software experience and need your help integrating or building a technical product with us." },
  { label: "TECH_COLLABORATION", text: "شفنا خبرتك في البرمجة والباك اند والواجهات ونحتاجك معنا في تنفيذ وربط مشروع تقني" },
  { label: "PROFESSIONAL_COLLABORATION", text: "We would like to collaborate with you on a professional project based on your experience. partnership consulting contribution collaboration" },
  { label: "PROFESSIONAL_COLLABORATION", text: "نرغب بالتعاون معك في مشروع اعتمادا على خبرتك. شراكة تعاون مهني استشارة مشاركة في مشروع" },
  { label: "EXPERIENCE_REQUEST", text: "Could you share your CV resume portfolio experience availability notice period salary expectations or examples of your work?" },
  { label: "EXPERIENCE_REQUEST", text: "هل يمكنك إرسال السيرة الذاتية أو البورتفوليو وذكر خبرتك وتوفرك وتوقعات الراتب ونماذج الأعمال" },
  { label: "OFFER", text: "We are pleased to offer you the position. Please review the employment offer, compensation package and proposed start date." },
  { label: "OFFER", text: "يسعدنا تقديم عرض وظيفي لك نرجو مراجعة العرض والراتب والمزايا وتاريخ المباشرة" },
  { label: "REJECTION", text: "After careful consideration we decided to move forward with other candidates. Unfortunately you were not selected for this role." },
  { label: "REJECTION", text: "نعتذر لم يتم اختيارك لهذه الفرصة وقررنا استكمال الإجراءات مع مرشحين آخرين نتمنى لك التوفيق" },
  { label: "NOT_RELEVANT", text: "Your bank statement invoice receipt payment card transaction verification code password reset account security notification" },
  { label: "NOT_RELEVANT", text: "كشف حساب فاتورة إيصال دفع رمز تحقق إعادة تعيين كلمة المرور إشعار أمني تسجيل دخول" },
  { label: "NOT_RELEVANT", text: "newsletter promotion discount sale order shipped delivery tracking social media notification new follower" },
  { label: "NOT_RELEVANT", text: "نشرة إخبارية خصم عرض متجر شحنة طلب توصيل متابع جديد إشعار حساب" },
  { label: "NOT_RELEVANT", text: "restaurant reservation personal travel booking family event appointment reminder streaming subscription receipt" }
];
